spring:
  main:
    lazy-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    async:
      request-timeout: -1

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  ai:
    provider: openai
    model: gpt-4.1-mini
    api-key: ${OPENAI_API_KEY}
    embedding-model: text-embedding-3-small
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/aicsassistant}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
